- name: stop chronyd
  systemd:
    name: chronyd
    state: stopped
    enabled: false

- name: install ntp
  yum:
    name: ntp
    state: installed

- name: copy ntp.conf
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
    - restart ntpd

- name: start ntpd
  systemd:
    name: ntpd
    enabled: yes
    daemon_reload: yes
    state: started
