---
ip: "{{ lookup('env', 'IP') }}"
app_home: /opt/lhasa
data_home: /mnt/data01

repo:
  server: 172.20.72.29
  http_port: 30081

registry:
  ip: 172.20.72.29
  port: 5000
  hostname: registry.ctfo.com
  username: admin
  password: ctfo@123
  data_dir: '{{ data_home }}/registry'

docker:
  data_dir: '{{ data_home }}/docker'

mysql8:
  data_dir: '{{ data_home }}/mysql8/data'
  tmp_dir:  '{{ data_home }}/mysql8/tmp'
  port: 33306
  root_password: Ctfo@123
  innodb_buffer_pool_size: 27917287424 # 26G

mysql57:
  data_dir: '{{ data_home }}/mysql57/data'
  port: 33206
  root_password: Ctfo@123
  innodb_buffer_pool_size: 27917287424 # 26G

postgresql:
  data_dir: '{{ data_home }}/postgresql'
  port: 35432
  max_connections: 1000
  superuser:
    name: postgres
    password: ctfo@123

nifi:
  home_dir: '{{ app_home }}/nifi-1.24.0'
  # partition_path: / # 数据文件所在分区
  username: admin
  password: admin@123456 # 至少12个字符
  port: 38443
  data_dir: '{{ data_home }}/nifi'
  log_history: 2
  jvm:
    xms: 4g
    xmx: 12g
  cluster:
    enabled: true
    protocol_port: 9192
    ui_autorefresh_interval: 5 sec
    flow_election_max_wait_time: 1 mins
    zk:
      embedded: true
      port: 12181
    servers:
      - dip-collector-01
      - dip-collector-02
      - dip-collector-03

dolphinscheduler:
  home_dir: '{{ app_home }}/dolphinscheduler'
  data_dir: '{{ data_home }}/dolphinscheduler'
  port: 32345

ntp:
  server: 54.11.0.65

superset:
  home_dir: '{{ app_home }}/superset'
  data_dir: '{{ data_home }}/superset'
  port: 38088

minio:
  data_dir: '{{ data_home }}/minio'
  console_port: 39090
  api_port: 39000

redis:
  home_dir: '{{ app_home }}/redis'
  data_dir: '{{ data_home }}/redis'
  password: ctfo@123
  bind_ip: 0.0.0.0
  port: 36379

activemq:
  home_dir: '{{ app_home }}/activemq'
  bind_ip: 0.0.0.0
  password: ctfo@123

kafka:
  home: /opt/kafka_2.12-2.8.2
  port: 19092
  data_dir: /mnt/data01/kafka2/logs
  data_retention_hours: 720 # 30 days
  zk:
    port: 12181
    data_dir: /mnt/data01/kafka2/zookeeper
  cluster:
    zk_prefix: 1
    servers:
      - 54.11.4.14
      - 54.11.4.15
      - 54.11.4.16
